service: slack-reactor

provider:
  name: aws
  runtime: nodejs6.10

functions:
  react:
    handler: handler.react
    description: Serverless Slack reactor Lambda function
    timeout: 60
    memorySize: 128
    events:
      - schedule:
          rate: cron(0 15 ? * MON-FRI *)
          input: ${file(${env:CONFIG_FILE})}
    environment:
      SLACK_API_TOKEN: ${env:SLACK_API_TOKEN}
