service: slack-reactor

provider:
  name: aws
  runtime: nodejs6.10

functions:
  react:
    handler: handler.react
    description: Serverless Slack reactor Lambda function
    timeout: 60
    memorySize: 128
    events:
      - schedule:
          rate: cron(0 16 ? * MON-FRI *)
          input:
            sample:
              pattern: 'test passed'
              emojis:
                - '+1'
              notifications:
                - user: '@jhon'
                  info: 'Just reacted with :{{emoji}}: in <{{permalink}}|#{{channel.name}}>!'
                  alert: 'Unable to react with :{{emoji}}:!'
                - user: '@jane'
                  info: 'Just reacted with :{{emoji}}: in <{{permalink}}|#{{channel.name}}>!'
    environment:
      SLACK_API_TOKEN: '<slack-api-token-here>'
